# Generated by Django 4.2.30 on 2026-05-14 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_adminuser_employee_loginactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='Force the user to change their password on next login.'),
        ),
    ]
