# Generated by Django 4.2.30 on 2026-05-14 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_adminuser_must_change_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='active_session_jti',
            field=models.CharField(blank=True, help_text='JTI of the currently active refresh token (single-device enforcement).', max_length=255, null=True),
        ),
    ]
