# Generated by Django 4.2.30 on 2026-05-15 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_adminuser_active_session_jti'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='last_activity',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the last token refresh — used to detect abandoned sessions.', null=True),
        ),
    ]
