# Generated by Django 4.2.30 on 2026-05-12 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='role',
            field=models.CharField(choices=[('IT', 'IT Manager'), ('MD', 'Managing Director'), ('HRM', 'HR Manager'), ('HR', 'Standard HR'), ('HOD', 'Head of Department'), ('HOD_ACCOUNTS', 'Accounts HOD')], max_length=20),
        ),
    ]
