# Generated by Django 4.2.30 on 2026-05-14 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_attendancerecord_id_alter_shift_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='absence_reason',
            field=models.CharField(blank=True, help_text='Reason for absence', max_length=255),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='arrival_time',
            field=models.CharField(blank=True, help_text='Time of arrival for late arrivals, e.g. 09:35', max_length=10),
        ),
    ]
