# Generated by Django 4.2.30 on 2026-07-02 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_alter_payroll_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payroll',
            old_name='bank_account',
            new_name='bank_account_usd',
        ),
        migrations.RenameField(
            model_name='payroll',
            old_name='bank_name',
            new_name='bank_name_usd',
        ),
        migrations.AddField(
            model_name='payroll',
            name='bank_account_zig',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='payroll',
            name='bank_name_zig',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
