# Generated by Django 4.2.30 on 2026-07-10 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_rename_bank_account_payroll_bank_account_usd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='daily_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='pay_type',
            field=models.CharField(choices=[('monthly', 'Monthly Salary'), ('daily', 'Daily Rate')], default='monthly', max_length=10),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='basic_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
