# Generated by Django 4.2.30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_site_employee_site'),
        ('payroll', '0005_payrolladjustment'),
    ]

    operations = [
        migrations.CreateModel(
            name='LongTermDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('number_of_months', models.PositiveIntegerField()),
                ('monthly_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('start_year', models.IntegerField()),
                ('start_month', models.IntegerField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=10)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=100)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='long_term_deductions', to='employees.employee')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]