# Generated by Django 4.2.30 on 2026-05-12 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('date_of_birth', models.DateField()),
                ('national_id', models.CharField(max_length=50, unique=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField()),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('employee_number', models.CharField(max_length=30, unique=True)),
                ('job_title', models.CharField(max_length=100)),
                ('date_joined', models.DateField()),
                ('employment_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract')], max_length=20)),
                ('status', models.CharField(choices=[('employed', 'Currently Employed'), ('retired', 'Retired'), ('dismissed', 'Dismissed'), ('resigned', 'Resigned'), ('suspended', 'Suspended')], default='employed', max_length=20)),
                ('status_reason', models.TextField(blank=True, help_text='Required if retired, dismissed, or suspended')),
                ('status_changed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='employees.department')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeStatusLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('reason', models.TextField()),
                ('changed_by', models.CharField(max_length=100)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='AcademicQualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('o_level', 'O Level'), ('a_level', 'A Level'), ('diploma', 'Diploma'), ('degree', 'Degree'), ('honours', 'Honours Degree'), ('masters', 'Masters'), ('phd', 'PhD'), ('certificate', 'Certificate'), ('other', 'Other')], max_length=20)),
                ('institution', models.CharField(max_length=200)),
                ('field_of_study', models.CharField(max_length=200)),
                ('year_obtained', models.PositiveIntegerField()),
                ('certificate', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='employees.employee')),
            ],
        ),
    ]
