# Generated by Django 4.2.30 on 2026-05-13 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_academicqualification_id_alter_department_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='contract_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='contract_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='employee_cvs/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='highest_education',
            field=models.CharField(blank=True, choices=[('o_level', 'O Level'), ('a_level', 'A Level'), ('certificate', 'Certificate'), ('diploma', 'Diploma'), ('degree', 'Degree'), ('honours', 'Honours Degree'), ('masters', 'Masters'), ('phd', 'PhD')], max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='highest_education_certificate',
            field=models.FileField(blank=True, null=True, upload_to='education_certs/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='nok_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='nok_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='employee',
            name='nok_full_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='employee',
            name='nok_national_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='nok_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='nok_relationship',
            field=models.CharField(blank=True, choices=[('spouse', 'Spouse'), ('parent', 'Parent'), ('sibling', 'Sibling'), ('child', 'Child'), ('guardian', 'Guardian'), ('friend', 'Friend'), ('other', 'Other')], max_length=50),
        ),
    ]
